### ISSUE TITLE
svue grades not working

### ISSUE THREAD

**Issue by peebowo** [g-kienzle/studentvue_cli#1]
i don't know much, if at all, about python. i was wondering if you know anything about my issue.

i pip3 installed studentvue_cli and ran through the setup of username, password, and district.

running "svue schedule" worked, but "svue grades" failed.

'''
Traceback (most recent call last):
  File "/usr/local/bin/svue", line 11, in <module>
    load_entry_point('studentvue-cli==0.7', 'console_scripts', 'svue')()
  File "/usr/local/lib/python3.7/dist-packages/studentvue_cli-0.7-py3.7.egg/studentvue_cli/studentvue_cli.py", line 150, in main
    fire.Fire(SVInfo)
  File "/usr/local/lib/python3.7/dist-packages/fire-0.4.0-py3.7.egg/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/usr/local/lib/python3.7/dist-packages/fire-0.4.0-py3.7.egg/fire/core.py", line 471, in _Fire
    target=component.__name__)
  File "/usr/local/lib/python3.7/dist-packages/fire-0.4.0-py3.7.egg/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/studentvue_cli-0.7-py3.7.egg/studentvue_cli/studentvue_cli.py", line 41, in grades
    c.get("Marks").get("Mark").get("Assignments").get("Assignment")
AttributeError: 'NoneType' object has no attribute 'get'
'''

any way you could fix this?

**Comment by g-kienzle** [comment]
I just released a new version of the package (install with `pip install studentvue-cli==0.8`), let me know if that fixes the issue. If not, let me know what the output of `svue grades` is

**Comment by peebowo** [comment]
its fixed now, just had to run it as root. tysm! didn't think you would respond lol

**Comment by peebowo** [comment]
the output is the grades, and it matches up with the web version too
